#!/usr/bin/env bash
# langs1-bignine_plus.sh
# de fr ru ar
# INCLUDE FREQ-LISTS(!)

#         ry-phrases
# ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_isl.txt
# ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_dan.txt
# ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_no-bokm.txt

# ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_ry.txt
# ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_ar.txt
# ~/dropbox-legacy/arphraseb_total.txt  # DECK + PRONUNC. + PDFRDS-LINKS:

# ~/SyncThing/rsc/Doks/Lang/fr/frapärmen-högstgymn.txt
## ~/Empire/Doks/Lang/fr/freq2000incontext.fra.txt

gvim \
    ~/SyncThing/rsc/Doks/Lang/lang-ry_sv-ry.txt \
    ~/SyncThing/rsc/Doks/Lang/de/lang-ty_ty-sv.txt \
    ~/SyncThing/rsc/Doks/Lang/de/tysteno.de.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_ty.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/2/Freq-De.txt \
    ~/SyncThing/rsc/Doks/Lang/fr/fragymn01.txt \
    ~/SyncThing/rsc/Doks/Lang/fr/frasteno.fr.txt \
    ~/SyncThing/rsc/Doks/Lang/fr/frdictmini.txt \
    ~/SyncThing/rsc/Doks/Lang/fr/FRPHRAS.txt \
    ~/SyncThing/rsc/Doks/Lang/fr/fragymn-4böckeravancplusövnbok.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_fra.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/2/Freq-Fra.txt \
    ~/SyncThing/rsc/Doks/Lang/ar/ar.blz-phras.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_ar.txt \
    ~/SyncThing/rsc/Doks/Lang/ru/lang-ry_ry-sv.txt \
    ~/SyncThing/rsc/Doks/Lang/ru/ryengphras_lplan.txt \
    ~/SyncThing/rsc/Doks/Lang/ru/toffry.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_ry2.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/freq_spa.txt \
    ~/SyncThing/rsc/data/lists/ref/lang/freq/2/Freq-Spa.txt \

    # da
    #   Dan-words Bornhack {{{
    # 
    #     genta
    #     ellers = annars
    #     trals
    #     nok = tillräckligt
    #     ha brug för
    #     blir her til
    #     udlevere
    #     ha tilbage = ha kvar
    #     finne ud
    #     børn
    #     vaske op
    # 
    #     heldigvis
    #     mangler
    # 
    #     undskyld
    #       selv tak
    #     det pleier at vare
    # 
    #     hvordæn gør man?
    #     lave
    #       afkørsel
    # 
    #     jeg kan got lige at
    #       huske
    #     rætning
    #         fem på syv
    # 
    #     i nærheden av
    #       hvordan
    #     nemmeste skul være at ...
    #     smuk/flott
    #     Det er jeg ked af
    #     mulighet
    #     Hvad anbefaler du?
    #       anden, hinanden
    #     Er det langt væk?
    #     dreje
    # 
    #     sort
    #     vi trænger at finne på
    #     vis man vil finne på
    # 
    #     hvor meget
    #     hvordan 
    # 
    #     leje (=hyra)
    #       vi er faret vild
    # 
    #     jeg har brug for
    # 
    #     genbruk
    # 
    #   }}}
    #   https://www.youtube.com/@p3essensen/videos  __da
    #     ~/Empire/Doks/Lang/da/språkdanska-antecknnordiska.pdf
    #   ~/SyncThing/rsc/Doks/Lang/da/dan_dsmil.txt
    # de
    #   https://www.youtube.com/@derspiegel/videos
    #   https://www.youtube.com/@dwdeutsch/videos  __de  #+AUTOGENERATED SUBTITLES
    #   https://www.youtube.com/@Bundeswehr/videos  __de
    # ~/SyncThing/rsc/Doks/Lang/de/mosal-phraseb_de.txt
    # Acr Eg de (Assassins Creed - Ancient Egypt Tour, German) {{{
    # 
    # ~/legacy/Pictures/0_acr-egde/*.mp4
    # 
    # ~/legacy/Pictures/acr-egdetest/acr-egde01.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde01.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde02.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde03.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde04.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde05.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde06.mp4
    # ~/legacy/Pictures/0_acr-egde/acr-egde07-3av18.mp4
    # 
    # ~/legacy/Pictures/0_acr-egde/acr-egde08-3av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde08-03av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde09-3av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde09-03av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde10-4av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde10-04av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde11-4av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde11-04av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde12-4av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde12-04av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde13-5av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde13-05av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde14-5av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde14-05av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde15-5av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde15-05av18.txt
    # ~/legacy/Pictures/0_acr-egde/acr-egde15b-5av18.mp4
    #     ~/Empire/Dropbox/rsc/transcr/Acr.de/acr-egde15b-05av18.txt
    # 
    # }}}
    #   https://www.sueddeutsche.de/
    # fr
    #   https://www.youtube.com/results?search_query=france+24+en+direct
    #   https://www.youtube.com/@FRANCE24/videos  __fr #download + win10-process
    # 
    # ar
    #   Lists + pdfrds-links:
    # . {{{
    # bad ~/SyncThing/rsc/Doks/Lang/ar/ar.blz-phras.txt
    # 
    # deck (no pronunc.data):
    #   ~/Dropbox/rsc/data/lists/learnqna/vanki/decks/lang/ar.va.txt
    # 
    #         ## ~/dropbox-legacy/arabiska/Ca_langc_ar_Arabicphrasebook.txt
    #  ~/Empire/Doks/Lang/ar/arabphras-berl.txt
    #  ~/Dropbox/rsc/data/lists/ref/lang/ar.blz-phras.txt
    # 
    #     ~/Dropbox/rsc/data/lists/at/l.ar.txt
    #     ~/dropbox-legacy/arabiska/Ca_langc_ar-5_BasicVerbs.txt
    #     ~/Dropbox/rsc/data/lists/ref/lang/freq/freq_ar.txt
    #     ~/dropbox-legacy/arabicverbs_basiclist.txt
    #     ~/dropbox-legacy/arabiska/arabiskverbböjning_plus_genitivackusativ.txt
    #     ~/dropbox-legacy/arabic.txt
    # 
    # }}}

