let b:keymap_name = "russian"
" https://en.wikipedia.org/wiki/Russian_alphabet  handwritten

loadkeymap
a а " CYRILLIC SMALL LETTER A
b б " CYRILLIC SMALL LETTER BE
v в " CYRILLIC SMALL LETTER VE
g г " CYRILLIC SMALL LETTER GHE
d д " CYRILLIC SMALL LETTER DE
e е " CYRILLIC SMALL LETTER IE
Z ж " CYRILLIC SMALL LETTER ZHE
z з " CYRILLIC SMALL LETTER ZE
i и " CYRILLIC SMALL LETTER I
j й " CYRILLIC SMALL LETTER SHORT I
к k " CYRILLIC SMALL LETTER KA
l л " CYRILLIC SMALL LETTER EL
m м " CYRILLIC SMALL LETTER EM
n н " CYRILLIC SMALL LETTER EN
o о " CYRILLIC SMALL LETTER O
p п " CYRILLIC SMALL LETTER PE
r р " CYRILLIC SMALL LETTER ER
s с " CYRILLIC SMALL LETTER ES
t т " CYRILLIC SMALL LETTER TE
u у " CYRILLIC SMALL LETTER U
f ф " CYRILLIC SMALL LETTER EF
H х " CYRILLIC SMALL LETTER HA
c ц " CYRILLIC SMALL LETTER TSE
C ч " CYRILLIC SMALL LETTER CHE
S ш " CYRILLIC SMALL LETTER SHA
" 0449 щ CYRILLIC SMALL LETTER SHCHA  =Z?
" 044A ъ CYRILLIC SMALL LETTER HARD SIGN  ="
y ы " CYRILLIC SMALL LETTER YERU
" 044C ь CYRILLIC SMALL LETTER SOFT SIGN
E э " CYRILLIC SMALL LETTER E
U ю " CYRILLIC SMALL LETTER YU
A я " CYRILLIC SMALL LETTER YA
Å ё " CYRILLIC SMALL LETTER IO
" → 0185 ƅ latin small letter tone six
" → A64F ꙏ cyrillic small letter neutral yer
" → A651 ꙑ cyrillic small letter yeru with back yer

" Cyrillic extensions
" 0450 ѐ CYRILLIC SMALL LETTER IE WITH GRAVE
" • Macedonian
" ≡ 0435 е 0300 $̀
" • Russian, ...
" ≡ 0435 е 0308 $̈
" 0452 ђ CYRILLIC SMALL LETTER DJE
" • Serbian
" → 0111 đ latin small letter d with stroke
" 0453 ѓ CYRILLIC SMALL LETTER GJE
" • Macedonian
" ≡ 0433 г 0301 $́
" 0454 є CYRILLIC SMALL LETTER UKRAINIAN IE
" = Old Cyrillic yest
" Cyrillic extensions
" 0400 Ѐ CYRILLIC CAPITAL LETTER IE WITH GRAVE
" ≡ 0415 Е 0300 $̀
" 0401 Ё CYRILLIC CAPITAL LETTER IO
" ≡ 0415 Е 0308 $̈
" 0402 Ђ CYRILLIC CAPITAL LETTER DJE
" 0403 Ѓ CYRILLIC CAPITAL LETTER GJE
" ≡ 0413 Г 0301 $́
" 0404 Є CYRILLIC CAPITAL LETTER UKRAINIAN IE
" 0405 Ѕ CYRILLIC CAPITAL LETTER DZE
" 0406 І CYRILLIC CAPITAL LETTER BYELORUSSIAN-
" UKRAINIAN I
" → 0049 I latin capital letter i
" → 0456 і cyrillic small letter byelorussian-
" ukrainian i
" → 04C0 Ӏ cyrillic letter palochka
" 0407 Ї CYRILLIC CAPITAL LETTER YI
" ≡ 0406 І 0308 $̈
" 0408 Ј CYRILLIC CAPITAL LETTER JE
" 0409 Љ CYRILLIC CAPITAL LETTER LJE
" 040A Њ CYRILLIC CAPITAL LETTER NJE
" 040B Ћ CYRILLIC CAPITAL LETTER TSHE
" 040C Ќ CYRILLIC CAPITAL LETTER KJE
" ≡ 041A К 0301 $́
" 040D Ѝ CYRILLIC CAPITAL LETTER I WITH GRAVE
" ≡ 0418 И 0300 $̀
" 040E Ў CYRILLIC CAPITAL LETTER SHORT U
" ≡ 0423 У 0306 $̆
" 040F Џ CYRILLIC CAPITAL LETTER DZHE
" Basic Russian alphabet
" 0410 А CYRILLIC CAPITAL LETTER A
" 0411 Б CYRILLIC CAPITAL LETTER BE
" → 0183 ƃ latin small letter b with topbar
" 0412 В CYRILLIC CAPITAL LETTER VE
" 0413 Г CYRILLIC CAPITAL LETTER GHE
" 0414 Д CYRILLIC CAPITAL LETTER DE
" 0415 Е CYRILLIC CAPITAL LETTER IE
" 0416 Ж CYRILLIC CAPITAL LETTER ZHE
" 0417 З CYRILLIC CAPITAL LETTER ZE
" 0418 И CYRILLIC CAPITAL LETTER I
" This letter is also used to represent electrolarynx
" phonation in the Voice Quality Symbols for
" extended IPA.
" 0419 Й CYRILLIC CAPITAL LETTER SHORT I
" ≡ 0418 И 0306 $̆
" 041A К CYRILLIC CAPITAL LETTER KA
" 041B Л CYRILLIC CAPITAL LETTER EL
" 041C М CYRILLIC CAPITAL LETTER EM
" 041D Н CYRILLIC CAPITAL LETTER EN
" 041E О CYRILLIC CAPITAL LETTER O
" 041F П CYRILLIC CAPITAL LETTER PE
" 0420 Р CYRILLIC CAPITAL LETTER ER
" 0421 С CYRILLIC CAPITAL LETTER ES
" 0422 Т CYRILLIC CAPITAL LETTER TE
" 0423 У CYRILLIC CAPITAL LETTER U
" → 0478 Ѹ cyrillic capital letter uk
" → 04AF ү cyrillic small letter straight u
" → A64A Ꙋ cyrillic capital letter monograph uk
" 0424 Ф CYRILLIC CAPITAL LETTER EF
" 0425 Х CYRILLIC CAPITAL LETTER HA
" 0426 Ц CYRILLIC CAPITAL LETTER TSE
" 0427 Ч CYRILLIC CAPITAL LETTER CHE
" The Unicode Standard, Version 17.0, Copyright © 1991-2025 Unicode, Inc. All rights reserved. 44
" 0485Cyrillic0455
" 046F ѯ CYRILLIC SMALL LETTER KSI
" 0470 Ѱ CYRILLIC CAPITAL LETTER PSI
" 0471 ѱ CYRILLIC SMALL LETTER PSI
" 0472 Ѳ CYRILLIC CAPITAL LETTER FITA
" 0473 ѳ CYRILLIC SMALL LETTER FITA
" → 0275 ɵ latin small letter barred o
" → 03B8 θ greek small letter theta
" 0474 Ѵ CYRILLIC CAPITAL LETTER IZHITSA
" 0475 ѵ CYRILLIC SMALL LETTER IZHITSA
" 0476 Ѷ CYRILLIC CAPITAL LETTER IZHITSA WITH
" DOUBLE GRAVE ACCENT
" ≡ 0474 Ѵ 030F $̏
" 0477 ѷ CYRILLIC SMALL LETTER IZHITSA WITH
" DOUBLE GRAVE ACCENT
" ≡ 0475 ѵ 030F $̏
" Historic digraphs
" These characters may be rendered as either digraph or
" monograph forms, with preferred alternative
" representations.
" 0478 Ѹ CYRILLIC CAPITAL LETTER UK
" • for “digraph onik” the preferred spelling is
" 041E О 0443 у
" • for “monograph uk” the preferred character is
" A64A Ꙋ
" → 0423 У cyrillic capital letter u
" 0479 ѹ CYRILLIC SMALL LETTER UK
" • for “digraph onik” the preferred spelling is
" 043E о 0443 у
" • for “monograph uk” the preferred character is
" A64B ꙋ
" Historic letters
" 047A Ѻ CYRILLIC CAPITAL LETTER ROUND OMEGA
" 047B ѻ CYRILLIC SMALL LETTER ROUND OMEGA
" 047C Ѽ CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
" = Cyrillic "beautiful omega"
" • despite its name, this character does not have a
" titlo, nor is it composed of an omega plus a
" diacritic
" → A64C Ꙍ cyrillic capital letter broad omega
" 047D ѽ CYRILLIC SMALL LETTER OMEGA WITH TITLO
" → 1F66 ὦ greek small letter omega with psili
" and perispomeni
" 047E Ѿ CYRILLIC CAPITAL LETTER OT
" 047F ѿ CYRILLIC SMALL LETTER OT
" 0480 Ҁ CYRILLIC CAPITAL LETTER KOPPA
" 0481 ҁ CYRILLIC SMALL LETTER KOPPA
" Historic miscellaneous
" 0482 ҂ CYRILLIC THOUSANDS SIGN
" 0483 $҃ COMBINING CYRILLIC TITLO
" • not used with titlo letters
" → A66F $꙯ combining cyrillic vzmet
" 0484 $҄ COMBINING CYRILLIC PALATALIZATION
" • not used for kamora
" → 02BC ʼ modifier letter apostrophe
" → 0311 $̑ combining inverted breve
" 0485 $҅ COMBINING CYRILLIC DASIA PNEUMATA
" → 0314 $̔ combining reversed comma above
" → 1AE1 $᫡ combining right tack above
" → 2CF0 $⳰ coptic combining spiritus asper
" 0455 ѕ CYRILLIC SMALL LETTER DZE
" • Macedonian
" → A643 ꙃ cyrillic small letter dzelo
" 0456 і CYRILLIC SMALL LETTER BYELORUSSIAN-
" UKRAINIAN I
" = Old Cyrillic i
" 0457 ї CYRILLIC SMALL LETTER YI
" • Ukrainian
" ≡ 0456 і 0308 $̈
" 0458 ј CYRILLIC SMALL LETTER JE
" • Serbian, Azerbaijani, Altay
" 0459 љ CYRILLIC SMALL LETTER LJE
" • Serbian, Macedonian
" → 01C9 ǉ latin small letter lj
" 045A њ CYRILLIC SMALL LETTER NJE
" • Serbian, Macedonian
" → 01CC ǌ latin small letter nj
" 045B ћ CYRILLIC SMALL LETTER TSHE
" • Serbian
" → 0107 ć latin small letter c with acute
" → 0127 ħ latin small letter h with stroke
" → 040B Ћ cyrillic capital letter tshe
" → 210F ℏ planck constant over two pi
" → A649 ꙉ cyrillic small letter djerv
" 045C ќ CYRILLIC SMALL LETTER KJE
" • Macedonian
" ≡ 043A к 0301 $́
" 045D ѝ CYRILLIC SMALL LETTER I WITH GRAVE
" • Macedonian, Bulgarian
" ≡ 0438 и 0300 $̀
" 045E ў CYRILLIC SMALL LETTER SHORT U
" • Byelorussian, Uzbek
" ≡ 0443 у 0306 $̆
" 045F џ CYRILLIC SMALL LETTER DZHE
" • Serbian, Macedonian, Abkhasian
" → 01C6 ǆ latin small letter dz with caron
" Historic letters
" 0460 Ѡ CYRILLIC CAPITAL LETTER OMEGA
" 0461 ѡ CYRILLIC SMALL LETTER OMEGA
" → A64D ꙍ cyrillic small letter broad omega
" 0462 Ѣ CYRILLIC CAPITAL LETTER YAT
" 0463 ѣ CYRILLIC SMALL LETTER YAT
" → A653 ꙓ cyrillic small letter iotified yat
" → AB60 ꭠ latin small letter sakha yat
" 0464 Ѥ CYRILLIC CAPITAL LETTER IOTIFIED E
" 0465 ѥ CYRILLIC SMALL LETTER IOTIFIED E
" → AB61 ꭡ latin small letter iotified e
" 0466 Ѧ CYRILLIC CAPITAL LETTER LITTLE YUS
" 0467 ѧ CYRILLIC SMALL LETTER LITTLE YUS
" → A659 ꙙ cyrillic small letter closed little yus
" → A65B ꙛ cyrillic small letter blended yus
" 0468 Ѩ CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
" 0469 ѩ CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
" → 044F я cyrillic small letter ya
" → A65D ꙝ cyrillic small letter iotified closed little
" yus
" 046A Ѫ CYRILLIC CAPITAL LETTER BIG YUS
" 046B ѫ CYRILLIC SMALL LETTER BIG YUS
" → A65B ꙛ cyrillic small letter blended yus
" 046C Ѭ CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
" 046D ѭ CYRILLIC SMALL LETTER IOTIFIED BIG YUS
" 046E Ѯ CYRILLIC CAPITAL LETTER KSI
" The Unicode Standard, Version 17.0, Copyright © 1991-2025 Unicode, Inc. All rights reserved. 45
" 04BECyrillic0486
" 04A3 ң CYRILLIC SMALL LETTER EN WITH DESCENDER
" • Bashkir, ...
" 04A4 Ҥ CYRILLIC CAPITAL LIGATURE EN GHE
" 04A5 ҥ CYRILLIC SMALL LIGATURE EN GHE
" • Altay, Mari, Yakut
" • also used for soft en in Old Church Slavonic
" • this is not a decomposable ligature
" 04A6 Ҧ CYRILLIC CAPITAL LETTER PE WITH MIDDLE
" HOOK
" 04A7 ҧ CYRILLIC SMALL LETTER PE WITH MIDDLE
" HOOK
" • older orthographies for Abkhasian
" 04A8 Ҩ CYRILLIC CAPITAL LETTER ABKHASIAN HA
" 04A9 ҩ CYRILLIC SMALL LETTER ABKHASIAN HA
" 04AA Ҫ CYRILLIC CAPITAL LETTER ES WITH DESCENDER
" 04AB ҫ CYRILLIC SMALL LETTER ES WITH DESCENDER
" • Bashkir, Chuvash
" • letterforms with right hooks are preferred,
" although occasional variants with left hooks
" occur
" • in Chuvashia, letterforms identical to or similar
" in form to 00E7 ç regularly occur
" 04AC Ҭ CYRILLIC CAPITAL LETTER TE WITH DESCENDER
" 04AD ҭ CYRILLIC SMALL LETTER TE WITH DESCENDER
" • Abkhasian
" 04AE Ү CYRILLIC CAPITAL LETTER STRAIGHT U
" 04AF ү CYRILLIC SMALL LETTER STRAIGHT U
" • stem is straight, unlike LETTER U
" • Azerbaijani, Bashkir, ...
" → 0423 У cyrillic capital letter u
" 04B0 Ұ CYRILLIC CAPITAL LETTER STRAIGHT U WITH
" STROKE
" 04B1 ұ CYRILLIC SMALL LETTER STRAIGHT U WITH
" STROKE
" • Kazakh
" 04B2 Ҳ CYRILLIC CAPITAL LETTER HA WITH
" DESCENDER
" 04B3 ҳ CYRILLIC SMALL LETTER HA WITH DESCENDER
" • Abkhasian, Tajik, Uzbek
" 04B4 Ҵ CYRILLIC CAPITAL LIGATURE TE TSE
" 04B5 ҵ CYRILLIC SMALL LIGATURE TE TSE
" • Abkhasian
" • this is not a decomposable ligature
" 04B6 Ҷ CYRILLIC CAPITAL LETTER CHE WITH
" DESCENDER
" 04B7 ҷ CYRILLIC SMALL LETTER CHE WITH
" DESCENDER
" • Abkhasian, Tajik
" 04B8 Ҹ CYRILLIC CAPITAL LETTER CHE WITH VERTICAL
" STROKE
" 04B9 ҹ CYRILLIC SMALL LETTER CHE WITH VERTICAL
" STROKE
" • Azerbaijani
" 04BA Һ CYRILLIC CAPITAL LETTER SHHA
" 04BB һ CYRILLIC SMALL LETTER SHHA
" • originally derived from Latin “h”, but uppercase
" form 04BA Һ is closer to an inverted che
" (0427 Ч )
" • Azerbaijani, Bashkir, ...
" → 0068 h latin small letter h
" 04BC Ҽ CYRILLIC CAPITAL LETTER ABKHASIAN CHE
" 04BD ҽ CYRILLIC SMALL LETTER ABKHASIAN CHE
" 04BE Ҿ CYRILLIC CAPITAL LETTER ABKHASIAN CHE
" WITH DESCENDER
" 0486 $҆ COMBINING CYRILLIC PSILI PNEUMATA
" → 0313 $̓ combining comma above
" → 1AE0 $᫠ combining left tack above
" → 2CF1 $⳱ coptic combining spiritus lenis
" 0487 $҇ COMBINING CYRILLIC POKRYTIE
" • used only with titlo letters
" • also attested in Glagolitic
" → 0311 $̑ combining inverted breve
" → A66F $꙯ combining cyrillic vzmet
" 0488 $҈ COMBINING CYRILLIC HUNDRED THOUSANDS
" SIGN
" • use 20DD $l for ten thousands sign
" 0489 $҉ COMBINING CYRILLIC MILLIONS SIGN
" → A670 $꙰ combining cyrillic ten millions sign
" Extended Cyrillic
" 048A Ҋ CYRILLIC CAPITAL LETTER SHORT I WITH TAIL
" 048B ҋ CYRILLIC SMALL LETTER SHORT I WITH TAIL
" • Kildin Sami
" 048C Ҍ CYRILLIC CAPITAL LETTER SEMISOFT SIGN
" 048D ҍ CYRILLIC SMALL LETTER SEMISOFT SIGN
" • Kildin Sami
" 048E Ҏ CYRILLIC CAPITAL LETTER ER WITH TICK
" 048F ҏ CYRILLIC SMALL LETTER ER WITH TICK
" • Kildin Sami
" 0490 Ґ CYRILLIC CAPITAL LETTER GHE WITH UPTURN
" 0491 ґ CYRILLIC SMALL LETTER GHE WITH UPTURN
" • Ukrainian
" 0492 Ғ CYRILLIC CAPITAL LETTER GHE WITH STROKE
" 0493 ғ CYRILLIC SMALL LETTER GHE WITH STROKE
" • Azerbaijani, Bashkir, ...
" • full bar form preferred over half-barred “F”-type
" 0494 Ҕ CYRILLIC CAPITAL LETTER GHE WITH MIDDLE
" HOOK
" 0495 ҕ CYRILLIC SMALL LETTER GHE WITH MIDDLE
" HOOK
" • Yakut, older orthographies for Abkhasian
" 0496 Җ CYRILLIC CAPITAL LETTER ZHE WITH
" DESCENDER
" 0497 җ CYRILLIC SMALL LETTER ZHE WITH DESCENDER
" • Tatar, ...
" 0498 Ҙ CYRILLIC CAPITAL LETTER ZE WITH
" DESCENDER
" 0499 ҙ CYRILLIC SMALL LETTER ZE WITH DESCENDER
" • Bashkir
" • letterforms with right hooks are preferred,
" although occasional variants with left hooks
" occur
" 049A Қ CYRILLIC CAPITAL LETTER KA WITH
" DESCENDER
" 049B қ CYRILLIC SMALL LETTER KA WITH DESCENDER
" • Abkhasian, Tajik, ...
" 049C Ҝ CYRILLIC CAPITAL LETTER KA WITH VERTICAL
" STROKE
" 049D ҝ CYRILLIC SMALL LETTER KA WITH VERTICAL
" STROKE
" • Azerbaijani
" 049E Ҟ CYRILLIC CAPITAL LETTER KA WITH STROKE
" 049F ҟ CYRILLIC SMALL LETTER KA WITH STROKE
" • Abkhasian
" 04A0 Ҡ CYRILLIC CAPITAL LETTER BASHKIR KA
" 04A1 ҡ CYRILLIC SMALL LETTER BASHKIR KA
" 04A2 Ң CYRILLIC CAPITAL LETTER EN WITH
" DESCENDER
" The Unicode Standard, Version 17.0, Copyright © 1991-2025 Unicode, Inc. All rights reserved. 46
" 04F9Cyrillic04BF
" 04DD ӝ CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
" ≡ 0436 ж 0308 $̈
" 04DE Ӟ CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
" ≡ 0417 З 0308 $̈
" 04DF ӟ CYRILLIC SMALL LETTER ZE WITH DIAERESIS
" ≡ 0437 з 0308 $̈
" 04E0 Ӡ CYRILLIC CAPITAL LETTER ABKHASIAN DZE
" 04E1 ӡ CYRILLIC SMALL LETTER ABKHASIAN DZE
" → 0292 ʒ latin small letter ezh
" 04E2 Ӣ CYRILLIC CAPITAL LETTER I WITH MACRON
" ≡ 0418 И 0304 $̄
" 04E3 ӣ CYRILLIC SMALL LETTER I WITH MACRON
" ≡ 0438 и 0304 $̄
" 04E4 Ӥ CYRILLIC CAPITAL LETTER I WITH DIAERESIS
" ≡ 0418 И 0308 $̈
" 04E5 ӥ CYRILLIC SMALL LETTER I WITH DIAERESIS
" ≡ 0438 и 0308 $̈
" 04E6 Ӧ CYRILLIC CAPITAL LETTER O WITH DIAERESIS
" ≡ 041E О 0308 $̈
" 04E7 ӧ CYRILLIC SMALL LETTER O WITH DIAERESIS
" ≡ 043E о 0308 $̈
" 04E8 Ө CYRILLIC CAPITAL LETTER BARRED O
" 04E9 ө CYRILLIC SMALL LETTER BARRED O
" → 0275 ɵ latin small letter barred o
" 04EA Ӫ CYRILLIC CAPITAL LETTER BARRED O WITH
" DIAERESIS
" ≡ 04E8 Ө 0308 $̈
" 04EB ӫ CYRILLIC SMALL LETTER BARRED O WITH
" DIAERESIS
" ≡ 04E9 ө 0308 $̈
" 04EC Ӭ CYRILLIC CAPITAL LETTER E WITH DIAERESIS
" ≡ 042D Э 0308 $̈
" 04ED ӭ CYRILLIC SMALL LETTER E WITH DIAERESIS
" • Kildin Sami
" ≡ 044D э 0308 $̈
" 04EE Ӯ CYRILLIC CAPITAL LETTER U WITH MACRON
" ≡ 0423 У 0304 $̄
" 04EF ӯ CYRILLIC SMALL LETTER U WITH MACRON
" ≡ 0443 у 0304 $̄
" 04F0 Ӱ CYRILLIC CAPITAL LETTER U WITH DIAERESIS
" ≡ 0423 У 0308 $̈
" 04F1 ӱ CYRILLIC SMALL LETTER U WITH DIAERESIS
" ≡ 0443 у 0308 $̈
" 04F2 Ӳ CYRILLIC CAPITAL LETTER U WITH DOUBLE
" ACUTE
" ≡ 0423 У 030B $̋
" 04F3 ӳ CYRILLIC SMALL LETTER U WITH DOUBLE
" ACUTE
" ≡ 0443 у 030B $̋
" 04F4 Ӵ CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
" ≡ 0427 Ч 0308 $̈
" 04F5 ӵ CYRILLIC SMALL LETTER CHE WITH DIAERESIS
" ≡ 0447 ч 0308 $̈
" 04F6 Ӷ CYRILLIC CAPITAL LETTER GHE WITH
" DESCENDER
" 04F7 ӷ CYRILLIC SMALL LETTER GHE WITH
" DESCENDER
" • Yupik
" 04F8 Ӹ CYRILLIC CAPITAL LETTER YERU WITH
" DIAERESIS
" ≡ 042B Ы 0308 $̈
" 04F9 ӹ CYRILLIC SMALL LETTER YERU WITH DIAERESIS
" ≡ 044B ы 0308 $̈
" 04BF ҿ CYRILLIC SMALL LETTER ABKHASIAN CHE WITH
" DESCENDER
" • some older Abkhaz fonts show a descender
" shaped like a right hook (ogonek or reversed
" comma shape)
" 04C0 Ӏ CYRILLIC LETTER PALOCHKA
" • aspiration sign in many Caucasian languages
" • is usually not cased, but the formal lowercase is
" 04CF ӏ
" → 0049 I latin capital letter i
" → 0406 І cyrillic capital letter byelorussian-
" ukrainian i
" 04C1 Ӂ CYRILLIC CAPITAL LETTER ZHE WITH BREVE
" ≡ 0416 Ж 0306 $̆
" 04C2 ӂ CYRILLIC SMALL LETTER ZHE WITH BREVE
" • Moldavian
" ≡ 0436 ж 0306 $̆
" 04C3 Ӄ CYRILLIC CAPITAL LETTER KA WITH HOOK
" 04C4 ӄ CYRILLIC SMALL LETTER KA WITH HOOK
" • Chukchi
" 04C5 Ӆ CYRILLIC CAPITAL LETTER EL WITH TAIL
" 04C6 ӆ CYRILLIC SMALL LETTER EL WITH TAIL
" • Kildin Sami
" 04C7 Ӈ CYRILLIC CAPITAL LETTER EN WITH HOOK
" 04C8 ӈ CYRILLIC SMALL LETTER EN WITH HOOK
" • Chukchi
" 04C9 Ӊ CYRILLIC CAPITAL LETTER EN WITH TAIL
" 04CA ӊ CYRILLIC SMALL LETTER EN WITH TAIL
" • Kildin Sami
" 04CB Ӌ CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
" 04CC ӌ CYRILLIC SMALL LETTER KHAKASSIAN CHE
" 04CD Ӎ CYRILLIC CAPITAL LETTER EM WITH TAIL
" 04CE ӎ CYRILLIC SMALL LETTER EM WITH TAIL
" • Kildin Sami
" 04CF ӏ CYRILLIC SMALL LETTER PALOCHKA
" 04D0 Ӑ CYRILLIC CAPITAL LETTER A WITH BREVE
" ≡ 0410 А 0306 $̆
" 04D1 ӑ CYRILLIC SMALL LETTER A WITH BREVE
" ≡ 0430 а 0306 $̆
" 04D2 Ӓ CYRILLIC CAPITAL LETTER A WITH DIAERESIS
" ≡ 0410 А 0308 $̈
" 04D3 ӓ CYRILLIC SMALL LETTER A WITH DIAERESIS
" ≡ 0430 а 0308 $̈
" 04D4 Ӕ CYRILLIC CAPITAL LIGATURE A IE
" 04D5 ӕ CYRILLIC SMALL LIGATURE A IE
" • this is not a decomposable ligature
" → 00E6 æ latin small letter ae
" 04D6 Ӗ CYRILLIC CAPITAL LETTER IE WITH BREVE
" ≡ 0415 Е 0306 $̆
" 04D7 ӗ CYRILLIC SMALL LETTER IE WITH BREVE
" ≡ 0435 е 0306 $̆
" 04D8 Ә CYRILLIC CAPITAL LETTER SCHWA
" 04D9 ә CYRILLIC SMALL LETTER SCHWA
" → 0259 ə latin small letter schwa
" 04DA Ӛ CYRILLIC CAPITAL LETTER SCHWA WITH
" DIAERESIS
" ≡ 04D8 Ә 0308 $̈
" 04DB ӛ CYRILLIC SMALL LETTER SCHWA WITH
" DIAERESIS
" ≡ 04D9 ә 0308 $̈
" 04DC Ӝ CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
" ≡ 0416 Ж 0308 $̈
" The Unicode Standard, Version 17.0, Copyright © 1991-2025 Unicode, Inc. All rights reserved. 47
" 04FFCyrillic04FA
" Additions for Nivkh
" 04FA Ӻ CYRILLIC CAPITAL LETTER GHE WITH STROKE
" AND HOOK
" 04FB ӻ CYRILLIC SMALL LETTER GHE WITH STROKE
" AND HOOK
" 04FC Ӽ CYRILLIC CAPITAL LETTER HA WITH HOOK
" 04FD ӽ CYRILLIC SMALL LETTER HA WITH HOOK
" 04FE Ӿ CYRILLIC CAPITAL LETTER HA WITH STROKE
" 04FF ӿ CYRILLIC SMALL LETTER HA WITH STROKE
