(use-modules (gnu home)
             (gnu home services)
             (gnu services)
             (guix gexp))

;; This string contains the logic for your "Specialist" modes.
;; We keep it lazy (use-package + :defer) so it doesn't slow down startup.
(define emacs-cluster-logic
  (string-append
   ";;; Generated by Guix Home - Specialist Clusters\n\n"
   
   ;; 1. Scheme/Guile Cluster (High priority for you)
   "(use-package geiser-guile\n"
   "  :defer t\n"
   "  :mode (\"\\\\.scm\\\\'\" . scheme-mode)\n"
   "  :config (setq geiser-guile-binary \"guile\"))\n\n"
   
   ;; 2. Fennel Cluster (For your Ardour/Lua scripting)
   "(use-package fennel-mode\n"
   "  :defer t\n"
   "  :mode (\"\\\\.fnl\\\\'\" . fennel-mode))\n\n"
   
   ;; 3. Python Cluster
   "(use-package python\n"
   "  :defer t\n"
   "  :mode (\"\\\\.py\\\\'\" . python-mode))\n"))

(home-environment
 (services
  (list
   ;; Create the bridge file for Emacs
   (simple-service 'emacs-cluster-bridge
                   home-files-service-type
                   (list `(".emacs.d/guix-clusters.el" 
                           ,(plain-file "guix-clusters.el" emacs-cluster-logic)))))))
