(use-modules (gnu home)
             (gnu home services)
             (gnu home services shells)
             (gnu services)
             (guix gexp))

;; This string contains the logic for your "Specialist" modes.
;; We keep it lazy (use-package + :defer) so it doesn't slow down startup.
(define emacs-cluster-logic
  (string-append
   ";;; Generated by Guix Home - Specialist Clusters\n\n"

   ;; 1. Scheme/Guile Cluster (High priority for you)
   "(use-package geiser-guile\n"
   "  :defer t\n"
   "  :mode (\"\\\\.scm\\\\'\" . scheme-mode)\n"
   "  :config (setq geiser-guile-binary \"guile\"))\n\n"
  
   ;; 2. Fennel Cluster (For your Ardour/Lua scripting)
   "(use-package fennel-mode\n"
   "  :defer t\n"
   "  :mode (\"\\\\.fnl\\\\'\" . fennel-mode))\n\n"
  
   ;; 3. Python Cluster
   "(use-package python\n"
   "  :defer t\n"
   "  :mode (\"\\\\.py\\\\'\" . python-mode))\n"))

(home-environment
 (services
  (list
   ;; --- 1. THE NIX-GUIX BASH BRIDGE ---
   ;; This manages your .bash_profile and .bashrc via Guix
   (service home-bash-service-type
            (home-bash-configuration
             (guix-defaults? #t)
             ;; --- Aliases Moved From Nix ---
             (aliases
              '(("fleet-up" . "sudo nixos-rebuild switch --flake ~/conf/nix-fleet#high-end && ~/conf/nix-fleet/scripts/guix-sync.sh")
                ("e" . "emacsclient -c -a 'emacs'")
                ("ding" . "mpv /home/bluelegend/Dropbox/rsc/media/au/sfx/ding.sfx.mp3 > /dev/null 2>&1 &")
                ("au" . "mpv --no-video --term-osd-bar")))
             (bash-profile
              (list (plain-file "nix-login-bridge" "[[ -f ~/.bashrc ]] && . ~/.bashrc\n")))

             ;; 2. This runs for EVERY new terminal/tab
             (bashrc
              (list (plain-file "nix-foundation"
              ; (list (plain-file "nix-bridge"
                                "
# --- THE NIX FOUNDATION ---
# This restores GVim, PATH, and Nix variables
if [ -f \"/etc/profiles/per-user/bluelegend/etc/profile.d/hm-session-vars.sh\" ]; then
  . \"/etc/profiles/per-user/bluelegend/etc/profile.d/hm-session-vars.sh\"
fi

# The Direnv Hook
eval \"$(direnv hook bash)\"
")))))

   ;; --- 2. EMACS CLUSTER BRIDGE ---
   (simple-service 'emacs-cluster-bridge
                   home-files-service-type
                   (list `(".config/emacs/guix-clusters.el" 
                           ,(plain-file "guix-clusters.el" emacs-cluster-logic)))))))
