(use-modules (gnu home)
             (gnu home services)
             (gnu home services shells)
             (gnu services)
             (gnu packages)
             (guix gexp))

;; This string contains the logic for your "Specialist" modes.
;; We keep it lazy (use-package + :defer) so it doesn't slow down startup.
(define emacs-cluster-logic
  (string-append
   ";;; Generated by Guix Home - Specialist Clusters\n\n"

   ;; --- SILENCE NATIVE COMPILATION POPUPS ---
   ;; This stops Emacs from splitting your screen with harmless compiler warnings
   "(setq native-comp-async-report-warnings-errors 'silent)\n\n"

   ;; 1. Scheme/Guile Cluster (High priority for you)
   "(use-package geiser-guile\n"
   "  :defer t\n"
   "  :mode (\"\\\\.scm\\\\'\" . scheme-mode)\n"
   "  :hook (scheme-mode . geiser-mode)\n"
   "  :config\n"
   "  (setq geiser-guile-binary \"guile\")\n"
   "  (add-hook 'scheme-mode-hook\n"
   "            (lambda ()\n"
   "              (when (fboundp 'smartparens-strict-mode)\n"
   "                (smartparens-strict-mode +1))\n"
   "              (setq-local evil-shift-width 2))))\n\n"
  
   ;; 2. Fennel Cluster (For your Ardour/Lua scripting)
   "(use-package fennel-mode\n"
   "  :defer t\n"
   "  :mode (\"\\\\.fnl\\\\'\" . fennel-mode))\n\n"
  
   ;; 3. Python Cluster
   "(use-package python\n"
   "  :defer t\n"
   "  :mode (\"\\\\.py\\\\'\" . python-mode))\n\n"

   ;; 4. HyLang Cluster (Lisp-powering Python Scripting)
      "(use-package hy-mode\n"
   ;  "  :ensure t\n"
      "  :defer t\n"
      "  :mode \"\\\\.hy\\\\'\"\n"
      "  :init\n"
      "  (require 'comint)\n"
      "  (require 'python)\n"
      "  :config\n"
      "  (add-hook 'hy-mode-hook\n"
      "            (lambda ()\n"
      "              (font-lock-add-keywords nil lisp-font-lock-keywords)\n"
      "              (font-lock-mode +1)\n"
      "              (font-lock-ensure)\n"
      "              (when (fboundp 'smartparens-strict-mode)\n"
      "                (smartparens-strict-mode +1))\n"
      "              (setq-local evil-shift-width 2))))\n\n"

   ;; 5. Clojure Cluster
      "(use-package clojure-mode\n"
      "  :defer t\n"
      "  :mode (\"\\\\.clj\\\\'\" \"\\\\.cljs\\\\'\" \"\\\\.edn\\\\'\")\n"
      "  :config\n"
      "  (add-hook 'clojure-mode-hook\n"
      "            (lambda ()\n"
      "              (when (fboundp 'smartparens-strict-mode)\n"
      "                (smartparens-strict-mode +1))\n"
      "              (setq-local evil-shift-width 2))))\n\n"

      "(use-package cider\n"
      "  :defer t\n"
      "  :init\n"
      "  (setq cider-repl-display-help nil)\n" ; Keeps the REPL buffer clean
      "  (setq cider-jack-in-dependencies '())\n"
      "  (setq cider-lein-parameters \"\")\n"
      "  :hook (clojure-mode . cider-mode))\n\n"

      ;; Optional: Language Server Protocol Bridge for Hy/Python
      "(use-package eglot\n"
      "  :defer t\n"
      "  :hook ((hy-mode . eglot-ensure)))\n"))

(home-environment
 (packages
  (list (specification->package "emacs-hy-mode")
        (specification->package "emacs-geiser-guile")
        (specification->package "emacs-clojure-mode")
        (specification->package "emacs-cider")))

 (services
  (list
   ;; --- 1. THE NIX-GUIX BASH BRIDGE ---
   ;; This manages your .bash_profile and .bashrc via Guix
   (service home-bash-service-type
            (home-bash-configuration
             (guix-defaults? #t)
             ;; --- 2. ENVIRONMENT VARIABLES (INSERT HERE) ---
             (environment-variables
               '(("PATH" . "$HOME/.nix-profile/bin:$PATH")
                 ("DIRENV_LOG_FORMAT" . "")))

             ;; --- Aliases Moved From Nix ---
             (aliases
              '(("fleet-up" . "sudo nixos-rebuild switch --flake ~/conf/nix-fleet#high-end && ~/conf/nix-fleet/scripts/guix-sync.sh")
                ("home-up"  . "guix home reconfigure ~/conf/nix-fleet/guix-home/home-config.scm")
                ("e" . "emacsclient -c -a 'emacs'")
                ("ding" . "mpv /home/bluelegend/Dropbox/rsc/media/au/sfx/ding.sfx.mp3 > /dev/null 2>&1 &")
                ("au" . "mpv --no-video --term-osd-bar")))
             (bash-profile
              (list (plain-file "nix-login-bridge" "[[ -f ~/.bashrc ]] && . ~/.bashrc\n")))

             ;; 2. This runs for EVERY new terminal/tab
             (bashrc
              (list (plain-file "nix-foundation"
              ; (list (plain-file "nix-bridge"
                                "
# --- THE NIX FOUNDATION ---
# This restores GVim, PATH, and Nix variables
if [ -f \"/etc/profiles/per-user/bluelegend/etc/profile.d/hm-session-vars.sh\" ]; then
  . \"/etc/profiles/per-user/bluelegend/etc/profile.d/hm-session-vars.sh\"
fi

# The Direnv Hook
eval \"$(direnv hook bash)\"

# --- THE STARSHIP PROMPT ---
# This activates your Starship config managed by Nix
eval \"$(starship init bash)\"
")))))

   ;; --- 2. EMACS CLUSTER BRIDGE ---
   (simple-service 'emacs-cluster-bridge
                   home-files-service-type
                   (list `(".config/emacs/guix-clusters.el" 
                           ,(plain-file "guix-clusters.el" emacs-cluster-logic))))

   (simple-service 'supercollider-dirs
                   home-files-service-type
                   (list `(".local/share/SuperCollider/Extensions/.keep"
                           ,(plain-file "sc-extensions-keep" ""))))
   (simple-service 'nvim-lua-configs
                   home-files-service-type
                   (list
                     `(".config/nvim/lua/neovide.lua"
                       ,(plain-file "neovide.lua"
                         "if vim.g.neovide then
  vim.g.neovide_cursor_animation_length = 0
  vim.g.neovide_scroll_animation_length = 0
  vim.g.neovide_position_animation_length = 0
  vim.g.neovide_cursor_trail_size = 0
  vim.g.neovide_cursor_vfx_mode = \"\"
  vim.g.neovide_opacity = 0.9
  vim.g.neovide_normal_opacity = 0.9
end
"))
                     `(".config/nvim/lua/lsp-config.lua"
                       ,(plain-file "lsp-config.lua"
                         "-- LSP + Completion configuration
-- Managed via Guix Home - do not edit directly.

-- ── Completion (nvim-cmp) ────────────────────────────────────────────────
local cmp = require('cmp')

cmp.setup({
  completion = {
    autocomplete = false,
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>']     = cmp.mapping.abort(),
    ['<CR>']      = cmp.mapping.confirm({ select = false }),
    ['<Tab>']     = cmp.mapping.select_next_item(),
    ['<S-Tab>']   = cmp.mapping.select_prev_item(),
  }),
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'path' },
  }),
})

-- ── LSP capabilities ─────────────────────────────────────────────────────
local capabilities = require('cmp_nvim_lsp').default_capabilities()

-- ── Shared keymaps, attached when LSP starts on a buffer ─────────────────
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(ev)
    local map = function(keys, func, desc)
      vim.keymap.set('n', keys, func, { buffer = ev.buf, desc = desc })
    end
    map('gd',         vim.lsp.buf.definition,    'Go to definition')
    map('gr',         vim.lsp.buf.references,    'Find references')
    map('K',          vim.lsp.buf.hover,         'Hover documentation')
    map('<leader>rn', vim.lsp.buf.rename,        'Rename symbol')
    map('<leader>ca', vim.lsp.buf.code_action,   'Code action')
    map('[d',         vim.diagnostic.goto_prev,  'Previous diagnostic')
    map(']d',         vim.diagnostic.goto_next,  'Next diagnostic')
    map('<leader>e',  vim.diagnostic.open_float, 'Show diagnostic')
  end,
})

-- ── Language servers ──────────────────────────────────────────────────────
vim.lsp.config('pyright', {
  capabilities = capabilities,
  cmd          = { 'pyright-langserver', '--stdio' },
  filetypes    = { 'python' },
  root_markers = { 'pyproject.toml', 'setup.py', 'setup.cfg', '.git' },
  settings     = {
    python = {
      analysis = { autoSearchPaths = true, useLibraryCodeForTypes = true },
    },
  },
})
vim.lsp.enable('pyright')

vim.lsp.config('lua_ls', {
  capabilities = capabilities,
  cmd          = { 'lua-language-server' },
  filetypes    = { 'lua' },
  root_markers = { '.luarc.json', '.git' },
  settings     = {
    Lua = {
      runtime = { version = 'LuaJIT' },
      workspace = {
        checkThirdParty = false,
        library = vim.api.nvim_get_runtime_file('', true),
      },
      diagnostics = { globals = { 'vim' } },
      telemetry   = { enable = false },
    },
  },
})
vim.lsp.enable('lua_ls')
"))))
   )))
